spring:
  application:
    name: Books
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdbx5
    username: postgres
    password: SUP3RpostU$3R
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000 #20s
      minimum-idle: 2
      maximum-pool-size: 5
      max-lifetime: 900000 #15m
      jdbcUrl: jdbc:postgresql://localhost:5432/booksdbx5
      username: postgres
      password: SUP3RpostU$3R
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  aop:
    proxy-target-class: false
logging:
  level:
    root: info
    edu.spv.books.aop.LoggingAspect: debug
    com.zaxxer.hikari: debug
